edition: 1.0.0
name: hello-world-app
# access 是当前应用所需要的密钥信息配置：
# 密钥配置可以参考：https://www.serverless-devs.com/serverless-devs/command/config
# 密钥使用顺序可以参考：https://www.serverless-devs.com/serverless-devs/tool#密钥使用顺序与规范
access: default

vars: # 全局变量
  region: cn-hangzhou
  service:
    name: fc-web-application-test-custom-container
    description: hello world by serverless devs

services:
  fc-web-application-test-custom-container: # 业务名称/模块名称
    component: fc
    actions:
      pre-deploy: # 在deploy之前运行
        - component: fc build --use-docker --dockerfile ./code/Dockerfile
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: fc-web-application-test-custom-container
        description: hello world by serverless devs
        caPort: 9000
        memorySize: 1024
        timeout: 60
        runtime: custom-container
        customContainerConfig:
          image: registry-vpc.cn-hangzhou.aliyuncs.com/fc-demo2/blotter:1.8.4
          accelerationType: Default
        codeUri: ./code
        instanceType: e1
        instanceConcurrency: 20
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
          
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              methods:
                - GET
                - POST
